Add the loaded file info to the toolbar
HEXRD/hexrdgui pull request #1489
Opened 2023-05-31 20:44 UTC by bnmajor

Adds the list of file names to a tooltip in the toolbar at the bottom of the window. The full path is still available in the menu: `View>Loaded Images`

![files_tooltip](https://github.com/HEXRD/hexrdgui/assets/51238406/b1fff568-4cb2-4a7e-a8fc-b6bff763272d)

Fixes #1460

2023-06-01 20:48 UTC, psavery requested changes

2023-06-01 20:48 UTC, psavery commented on hexrd/ui/image_series_toolbar.py
> +                                        'file.svg', binary=True)
```suggestion
        data = resource_loader.load_resource(hexrd.ui.resources.icons,
                                             'file.svg', binary=True)
```

2023-06-01 20:48 UTC, psavery commented on hexrd/ui/image_series_toolbar.py
> +        self.toggle_widget_visibility(enable)
I think we should change this one back. It is possible for an image stack to be loaded with no omega information associated with it. If that's the case, the omega label should be invisible, but the slider and frame number should be visible.

2023-06-01 20:48 UTC, psavery commented on hexrd/ui/image_series_toolbar.py
> +        self.file_label.setToolTip(('\n').join(tips))
```suggestion
        self.file_label.setToolTip('\n'.join(tips))
```

2023-06-01 20:48 UTC, psavery commented on hexrd/ui/image_series_toolbar.py
> +                f'{det}: {(", ").join(fnames)}'
```suggestion
                f'{det}: {", ".join(fnames)}'
```

2023-06-01 21:10 UTC, psavery reviewed
@bnmajor Things to fix:

- [ ] Can we try to make the icon the same size as the other icons in the toolbar?
- [ ] Can we move the icon to be to the left of the matplotlib navigation toolbar icons, instead of to the right?
- [ ] We should eliminate the menu item that displays the file names as well.
- [ ] The image series toolbar doesn't keep sliding (see #1490). It appears this is because `set_visible()` is for some reason being called while the slider is moving, and there is a `set_visible(False)` followed by a `set_visible(True)`. Before, this didn't cause an issue because the `QWidget` parent had its visibility modified. But now that the QSlider has its visibility modified, it is turning off the interaction.

2023-06-02 13:32 UTC, bnmajor commented
> * [x]  Can we move the icon to be to the left of the matplotlib navigation toolbar icons, instead of to the right?

This is fixed in [e81e540](https://github.com/HEXRD/hexrdgui/pull/1489/commits/e81e540142b5bfbe73b5afcf4922d44f6c29d54b) by creating a third toolbar that is now positioned before the matplotlib toolbar. This also fixes the slider bug because the `ImageSeriesToolbar` behavior has been reverted and we are no longer toggling the visibility of individual widgets.

2023-06-02 13:34 UTC, bnmajor commented
> Can we try to make the icon the same size as the other icons in the toolbar?

I tried to match up the size a bit better but I think part of the reason they look so different is because of the button (in the nav bar) vs label (our tooltip) formatting. Happy to tweak it some more if that seems helpful.
![toolbars](https://github.com/HEXRD/hexrdgui/assets/51238406/ea85acc7-29ff-41a0-9d03-d6eb3ba231eb)

2023-06-03 17:47 UTC, psavery commented on hexrd/ui/hexrd_config.py
> -        state['euler_angle_convention'] = self.euler_angle_convention
I am deleting this because it seems repetitious. It should already be in the state.

2023-06-03 18:13 UTC, psavery commented on hexrd/ui/image_series_toolbar.py
> +class ImageSeriesInfoToolbar(QWidget):
Looks fine to me for now!

2023-06-03 18:14 UTC, psavery approved these changes
LGTM! I pushed a couple of minor changes as well (including making the icon a little bigger so it better matches with the other icons).

2023-06-05 12:35 UTC, bnmajor commented
> LGTM! I pushed a couple of minor changes as well (including making the icon a little bigger so it better matches with the other icons).

And here I made it smaller because I thought it looked bigger than the others... I do not have a good eye for these things :upside_down_face:

2023-06-05 12:35 UTC, merged